/*
     FILE ARCHIVED ON 10:15:28 avr. 25, 2013 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 19:29:28 déc. 3, 2016.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
// Random post and Recent Post by tag ver 1.0 
// by satankMKR/Makmur
// On 22 Jan 2013
// Visit: /web/20130425101528/http://mkr-site.blogspot.com
function RandomRecenTag(b){(function(m){var j={blogURL:"",MaxPost:5,RandompostActive:true,idcontaint:"#randompost",thumbSize:100,jumlahhuruf:100,cmtext:"comments",pBlank:"/web/20130425101528/http://2.bp.blogspot.com/-D47WWjFZXdk/UP1z-A5uCuI/AAAAAAAAH98/heTBvxq49No/s1600/noimage.jpg",NoCmtext:"No Comment",tagName:false};j=m.extend({},j,b);var k=m(j.idcontaint);if(j.blogURL==""){var a=window.location.protocol+"//"+window.location.host}else{var a=j.blogURL}var o=k.append('<ul class="rdmrcpostag"/>');var l=function(y){var D,i,c,h,B,z,C,f="",A=y.feed.entry;for(var d=0;d<A.length;d++){for(var e=0;e<A[d].link.length;e++){if(A[d].link[e].rel=="alternate"){D=A[d].link[e].href;break}}for(var g=0;g<A[d].link.length;g++){if(A[d].link[g].rel=="replies"&&A[d].link[g].type=="text/html"){c=A[d].link[g].title.split(" ")[0];break}}if(c!=0){h='<span class="cm">'+c+" "+j.cmtext+"</span>"}else{h='<span class="cm">'+j.NoCmtext+"</span>"}if("content" in A[d]){B=A[d].content.$t}else{if("summary" in A[d]){B=A[d].summary.$t}else{B=""}}if("media$thumbnail" in A[d]){z=A[d].media$thumbnail.url.replace(/\/s[0-9]+\-c/g,"/s"+j.thumbSize+"-c")}else{z=j.pBlank.replace(/\/s[0-9]+(\-c|\/)/,"/s"+j.thumbSize+"$1")}B=B.replace(/<\S[^>]*>/g,"");if(B.length>j.jumlahhuruf){B=B.substring(0,j.jumlahhuruf)+"..."}i=A[d].title.$t;C=A[d].published.$t.substring(0,10),C=C.replace(/-/g,"/");f+='<li><a class="thumbp" href="'+D+'" target="_blank"><img width="'+j.thumbSize+'" height="'+j.thumbSize+'" alt="'+i+'"src="'+z+'"/></a><b><a href="'+D+'" target="_blank">'+i+'</a></b><div class="datex"><span class="dt">'+C+"</span>"+h+'</div><p class="contxisi">'+B+"</p></li>"}m("ul",k).append(f)};var p=function(h){Total_Posts_Number=h.feed.openSearch$totalResults.$t;if(Total_Posts_Number<=j.MaxPost){j.MaxPost=Total_Posts_Number}var e=[];while(e.length<j.MaxPost){var f=Math.ceil(Math.random()*Total_Posts_Number);var g=false;for(var i=0;i<e.length;i++){if(e[i]==f){g=true;break}}if(!g){e[e.length]=f}}if(j.tagName==false){var c=""}else{var c="/-/"+j.tagName}if(j.RandompostActive==true){for(var d=0;d<j.MaxPost;d++){m.ajax({url:a+"/feeds/posts/default"+c+"?start-index="+e[d]+"&max-results=1&orderby=published&alt=json-in-script",success:l,dataType:"jsonp",cache:true})}}else{m.ajax({url:a+"/feeds/posts/default"+c+"?max-results="+j.MaxPost+"&orderby=published&alt=json-in-script",success:l,dataType:"jsonp",cache:true})}};var n=function(){if(j.tagName==false){m.ajax({url:a+"/feeds/posts/default?max-results=0&alt=json-in-script",success:p,dataType:"jsonp",cache:true})}else{m.ajax({url:a+"/feeds/posts/default/-/"+j.tagName+"?max-results=0&alt=json-in-script",success:p,dataType:"jsonp",cache:true})}};m(document).ready(n)})(jQuery)};